export type TalentName =
  | 'Technical Knock'
  | 'Weapon-Tech'
  | 'Bodyguard'
  | 'Deny the Witch'
  | 'Strong Minded'
  | 'Weapon Training (Las)'
  | 'Weapon Training (Solid Projectile)'
  | 'Weapon Training (Low-Tech)'
  | 'Weapon Training (Shock)'
  | 'Weapon Training (Flame)'
  | 'Weapon Training (Chain)'
  | 'Weapon Training (Low-Tech, Solid Projectile)'
  | 'Mechadendrite Use (Utility)'
  | 'Jaded'
  | 'Leap Up'
  | 'Resistance (Pick One)'
  | 'Takedown'
  | 'Catfall'
  | 'Quick Draw'
  | 'Double Team'
  | 'Hatred (Choose Group)'
  | 'Hatred (Daemons)'
  | 'Resistance (Psychic Powers)'
  | 'Warp Sense'
  | 'Ambidextrous'
  | 'Clues from the Crowds'
  | 'Keen Intuition'
  | 'Disarm'
  | 'Iron Jaw'
  | 'Rapid Reload'
  | 'Peer (Criminal Cartels)'
  | 'Die Hard'
  | 'Flagellant'
  | 'Hard Target'
  | 'Hotshot Pilot';